 ######################################################################
# Automatically generated by qmake (2.01a) Wed May 15 16:57:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++0x
LIBS += libtetris.a


# Input
HEADERS += tetris.h \
    tetrisarea.h
SOURCES += main.cpp tetris.cpp \
    tetrisarea.cpp
